### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by Millielele** [gtzheng/AdvST#1]
Thanks for your excellent work!
When I want to reproduce the results on the DomainNet dataset, the process is killed by the Linux when the code runs the 3th epoch. 
Here is the problem:
[3] train_loss:3.8696 cls:2.9915 con:1.2808 ent 4.0269 lr:0.0010 val_acc:0.6480 (best)
Real Infograph:0.094500 Clipart:0.284500 Painting:0.328000 Quickdraw:0.031000 Sketch:0.212000 Mean:0.1
90000
Semantic image generation [iter 2]
Killed  

My GPU is  RTX A6000 , how to solve this problem?

**Comment by gtzheng** [comment]
Thank you for your interest in our work! I am also sorry for the late rely.

The problem arises from the default in-memory augmentation. That is, all augmented data is stored in memory. When the dataset is large, it is possible that the size of augmented data exceeds your physical memory.
To solve this problem, you could store the augmented data on disk. I have added the `ModelADASemanticsDisk` class for the DomainNet dataset. To use this class, simply add `--aug_folder /path/to/aug_data` when you run `main_domainnet.py`.

I haven't thoroughly tested the new class, but I believe it could give you an idea of how to solve this problem.
Thanks again for your interest.
