### ISSUE TITLE
how to use AdvST

### ISSUE THREAD

**Issue by ChannySwift** [gtzheng/AdvST#2]
Hello author, I have a question, how can I find the ϵ parameter in your paper in train_models_pace.py, so as to change AdvST-ME to AdvST model. Thanks

**Comment by gtzheng** [comment]
Thanks for your interest in our paper. The parameter you are looking for is here:
https://github.com/gtzheng/AdvST/blob/338f82d8879bc916dd89c880df49fca33942c10d/train_models_pacs.py#L42
Set `eta=0` for AdvST models.

**Comment by ChannySwift** [comment]
Thank you author
